[build]
publish = "build/"
command = "bun run build"

[[redirects]]
from = "/"
to = "/collection.json"
status = 200

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
