name: Update Search Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup bun.sh environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache buns dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Run bun install
        run: bun install --frozen-lockfile

      - name: Cache .iiif/cache
        uses: actions/cache@v4
        with:
          path: apps/iiif/.iiif/cache
          key: ${{ runner.os }}-iiif-cache-${{ hashFiles('apps/iiif/.iiifrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-iiif-cache-

      - name: Deploy to Search Index
        run: |
          bun run build --filter=iiif

      - name: Build IIIF Search
        working-directory: apps/static-site
        run: |
          bun run ./typesense-update.ts --recreate-index
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          TYPESENSE_URL: 63flhve71t2un5xgp.a1.typesense.net
          TYPESENSE_PORT: 443
          TYPESENSE_PROTOCOL: https
          TYPESENSE_COLLECTION_NAME: production-manifests
